spring.application.name=api.gpt

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/llm?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=mysql904#

#true ?? ? jpa ??? ?? ??
spring.jpa.show-sql=true

#DDL ??? DB? ?? ??? ?? ??
spring.jpa.hibernate.ddl-auto=update

# JPA? ???? Hibernate? ????? ??? SQL? ???? ???
spring.jpa.properties.hibernate.format_sql=true